/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardPortfolioRouteImport } from './routes/dashboard.portfolio'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardCompanyRouteImport } from './routes/dashboard.company'
import { Route as DashboardBookmarksRouteImport } from './routes/dashboard.bookmarks'
import { Route as DashboardApplicationsRouteImport } from './routes/dashboard.applications'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTagsRouteImport } from './routes/admin.tags'
import { Route as AdminSkillsRouteImport } from './routes/admin.skills'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminJobsRouteImport } from './routes/admin.jobs'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public.verify-email'
import { Route as PublicTermsRouteImport } from './routes/_public.terms'
import { Route as PublicSearchRouteImport } from './routes/_public.search'
import { Route as PublicResetPasswordRouteImport } from './routes/_public.reset-password'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as PublicPrivacyRouteImport } from './routes/_public.privacy'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public.forgot-password'
import { Route as PublicFaqRouteImport } from './routes/_public.faq'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard.jobs.index'
import { Route as PublicJobsIndexRouteImport } from './routes/_public.jobs.index'
import { Route as DashboardProfileEditRouteImport } from './routes/dashboard.profile.edit'
import { Route as DashboardJobsNewRouteImport } from './routes/dashboard.jobs.new'
import { Route as PublicJobsIdRouteImport } from './routes/_public.jobs.$id'
import { Route as PublicFreelancersIdRouteImport } from './routes/_public.freelancers.$id'
import { Route as PublicCompaniesIdRouteImport } from './routes/_public.companies.$id'
import { Route as DashboardJobsIdEditRouteImport } from './routes/dashboard.jobs.$id.edit'
import { Route as DashboardJobsIdApplicationsRouteImport } from './routes/dashboard.jobs.$id.applications'
import { Route as PublicJobsIdApplyRouteImport } from './routes/_public.jobs.$id_.apply'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfolioRoute = DashboardPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCompanyRoute = DashboardCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBookmarksRoute = DashboardBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApplicationsRoute = DashboardApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTagsRoute = AdminTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSkillsRoute = AdminSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminJobsRoute = AdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFaqRoute = PublicFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicJobsIndexRoute = PublicJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardProfileEditRoute = DashboardProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardProfileRoute,
} as any)
const DashboardJobsNewRoute = DashboardJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicJobsIdRoute = PublicJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicFreelancersIdRoute = PublicFreelancersIdRouteImport.update({
  id: '/freelancers/$id',
  path: '/freelancers/$id',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCompaniesIdRoute = PublicCompaniesIdRouteImport.update({
  id: '/companies/$id',
  path: '/companies/$id',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardJobsIdEditRoute = DashboardJobsIdEditRouteImport.update({
  id: '/jobs/$id/edit',
  path: '/jobs/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsIdApplicationsRoute =
  DashboardJobsIdApplicationsRouteImport.update({
    id: '/jobs/$id/applications',
    path: '/jobs/$id/applications',
    getParentRoute: () => DashboardRoute,
  } as any)
const PublicJobsIdApplyRoute = PublicJobsIdApplyRouteImport.update({
  id: '/jobs/$id_/apply',
  path: '/jobs/$id/apply',
  getParentRoute: () => PublicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/privacy': typeof PublicPrivacyRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/search': typeof PublicSearchRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/company': typeof DashboardCompanyRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/profile': typeof DashboardProfileRouteWithChildren
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/companies/$id': typeof PublicCompaniesIdRoute
  '/freelancers/$id': typeof PublicFreelancersIdRoute
  '/jobs/$id': typeof PublicJobsIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/jobs/': typeof PublicJobsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/jobs/$id/apply': typeof PublicJobsIdApplyRoute
  '/dashboard/jobs/$id/applications': typeof DashboardJobsIdApplicationsRoute
  '/dashboard/jobs/$id/edit': typeof DashboardJobsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/faq': typeof PublicFaqRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/login': typeof PublicLoginRoute
  '/privacy': typeof PublicPrivacyRoute
  '/register': typeof PublicRegisterRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/search': typeof PublicSearchRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/company': typeof DashboardCompanyRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/profile': typeof DashboardProfileRouteWithChildren
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/companies/$id': typeof PublicCompaniesIdRoute
  '/freelancers/$id': typeof PublicFreelancersIdRoute
  '/jobs/$id': typeof PublicJobsIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/jobs': typeof PublicJobsIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/jobs/$id/apply': typeof PublicJobsIdApplyRoute
  '/dashboard/jobs/$id/applications': typeof DashboardJobsIdApplicationsRoute
  '/dashboard/jobs/$id/edit': typeof DashboardJobsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/faq': typeof PublicFaqRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/search': typeof PublicSearchRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/jobs': typeof AdminJobsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/skills': typeof AdminSkillsRoute
  '/admin/tags': typeof AdminTagsRoute
  '/admin/users': typeof AdminUsersRoute
  '/dashboard/applications': typeof DashboardApplicationsRoute
  '/dashboard/bookmarks': typeof DashboardBookmarksRoute
  '/dashboard/company': typeof DashboardCompanyRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/portfolio': typeof DashboardPortfolioRoute
  '/dashboard/profile': typeof DashboardProfileRouteWithChildren
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/companies/$id': typeof PublicCompaniesIdRoute
  '/_public/freelancers/$id': typeof PublicFreelancersIdRoute
  '/_public/jobs/$id': typeof PublicJobsIdRoute
  '/dashboard/jobs/new': typeof DashboardJobsNewRoute
  '/dashboard/profile/edit': typeof DashboardProfileEditRoute
  '/_public/jobs/': typeof PublicJobsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/_public/jobs/$id_/apply': typeof PublicJobsIdApplyRoute
  '/dashboard/jobs/$id/applications': typeof DashboardJobsIdApplicationsRoute
  '/dashboard/jobs/$id/edit': typeof DashboardJobsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/about'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/jobs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/tags'
    | '/admin/users'
    | '/dashboard/applications'
    | '/dashboard/bookmarks'
    | '/dashboard/company'
    | '/dashboard/notifications'
    | '/dashboard/portfolio'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/companies/$id'
    | '/freelancers/$id'
    | '/jobs/$id'
    | '/dashboard/jobs/new'
    | '/dashboard/profile/edit'
    | '/jobs/'
    | '/dashboard/jobs/'
    | '/jobs/$id/apply'
    | '/dashboard/jobs/$id/applications'
    | '/dashboard/jobs/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/reset-password'
    | '/search'
    | '/terms'
    | '/verify-email'
    | '/admin/categories'
    | '/admin/jobs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/tags'
    | '/admin/users'
    | '/dashboard/applications'
    | '/dashboard/bookmarks'
    | '/dashboard/company'
    | '/dashboard/notifications'
    | '/dashboard/portfolio'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/companies/$id'
    | '/freelancers/$id'
    | '/jobs/$id'
    | '/dashboard/jobs/new'
    | '/dashboard/profile/edit'
    | '/jobs'
    | '/dashboard/jobs'
    | '/jobs/$id/apply'
    | '/dashboard/jobs/$id/applications'
    | '/dashboard/jobs/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_public'
    | '/admin'
    | '/dashboard'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/faq'
    | '/_public/forgot-password'
    | '/_public/login'
    | '/_public/privacy'
    | '/_public/register'
    | '/_public/reset-password'
    | '/_public/search'
    | '/_public/terms'
    | '/_public/verify-email'
    | '/admin/categories'
    | '/admin/jobs'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/skills'
    | '/admin/tags'
    | '/admin/users'
    | '/dashboard/applications'
    | '/dashboard/bookmarks'
    | '/dashboard/company'
    | '/dashboard/notifications'
    | '/dashboard/portfolio'
    | '/dashboard/profile'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/_public/companies/$id'
    | '/_public/freelancers/$id'
    | '/_public/jobs/$id'
    | '/dashboard/jobs/new'
    | '/dashboard/profile/edit'
    | '/_public/jobs/'
    | '/dashboard/jobs/'
    | '/_public/jobs/$id_/apply'
    | '/dashboard/jobs/$id/applications'
    | '/dashboard/jobs/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolio': {
      id: '/dashboard/portfolio'
      path: '/portfolio'
      fullPath: '/dashboard/portfolio'
      preLoaderRoute: typeof DashboardPortfolioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/company': {
      id: '/dashboard/company'
      path: '/company'
      fullPath: '/dashboard/company'
      preLoaderRoute: typeof DashboardCompanyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bookmarks': {
      id: '/dashboard/bookmarks'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof DashboardBookmarksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/applications': {
      id: '/dashboard/applications'
      path: '/applications'
      fullPath: '/dashboard/applications'
      preLoaderRoute: typeof DashboardApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tags': {
      id: '/admin/tags'
      path: '/tags'
      fullPath: '/admin/tags'
      preLoaderRoute: typeof AdminTagsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/skills': {
      id: '/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AdminSkillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/jobs': {
      id: '/admin/jobs'
      path: '/jobs'
      fullPath: '/admin/jobs'
      preLoaderRoute: typeof AdminJobsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/faq': {
      id: '/_public/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicFaqRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/jobs'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/jobs/': {
      id: '/_public/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof PublicJobsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/profile/edit': {
      id: '/dashboard/profile/edit'
      path: '/edit'
      fullPath: '/dashboard/profile/edit'
      preLoaderRoute: typeof DashboardProfileEditRouteImport
      parentRoute: typeof DashboardProfileRoute
    }
    '/dashboard/jobs/new': {
      id: '/dashboard/jobs/new'
      path: '/jobs/new'
      fullPath: '/dashboard/jobs/new'
      preLoaderRoute: typeof DashboardJobsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/jobs/$id': {
      id: '/_public/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof PublicJobsIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/freelancers/$id': {
      id: '/_public/freelancers/$id'
      path: '/freelancers/$id'
      fullPath: '/freelancers/$id'
      preLoaderRoute: typeof PublicFreelancersIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/companies/$id': {
      id: '/_public/companies/$id'
      path: '/companies/$id'
      fullPath: '/companies/$id'
      preLoaderRoute: typeof PublicCompaniesIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/jobs/$id/edit': {
      id: '/dashboard/jobs/$id/edit'
      path: '/jobs/$id/edit'
      fullPath: '/dashboard/jobs/$id/edit'
      preLoaderRoute: typeof DashboardJobsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs/$id/applications': {
      id: '/dashboard/jobs/$id/applications'
      path: '/jobs/$id/applications'
      fullPath: '/dashboard/jobs/$id/applications'
      preLoaderRoute: typeof DashboardJobsIdApplicationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/jobs/$id_/apply': {
      id: '/_public/jobs/$id_/apply'
      path: '/jobs/$id/apply'
      fullPath: '/jobs/$id/apply'
      preLoaderRoute: typeof PublicJobsIdApplyRouteImport
      parentRoute: typeof PublicRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicFaqRoute: typeof PublicFaqRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicCompaniesIdRoute: typeof PublicCompaniesIdRoute
  PublicFreelancersIdRoute: typeof PublicFreelancersIdRoute
  PublicJobsIdRoute: typeof PublicJobsIdRoute
  PublicJobsIndexRoute: typeof PublicJobsIndexRoute
  PublicJobsIdApplyRoute: typeof PublicJobsIdApplyRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicFaqRoute: PublicFaqRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicCompaniesIdRoute: PublicCompaniesIdRoute,
  PublicFreelancersIdRoute: PublicFreelancersIdRoute,
  PublicJobsIdRoute: PublicJobsIdRoute,
  PublicJobsIndexRoute: PublicJobsIndexRoute,
  PublicJobsIdApplyRoute: PublicJobsIdApplyRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminJobsRoute: typeof AdminJobsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSkillsRoute: typeof AdminSkillsRoute
  AdminTagsRoute: typeof AdminTagsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminJobsRoute: AdminJobsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSkillsRoute: AdminSkillsRoute,
  AdminTagsRoute: AdminTagsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardProfileRouteChildren {
  DashboardProfileEditRoute: typeof DashboardProfileEditRoute
}

const DashboardProfileRouteChildren: DashboardProfileRouteChildren = {
  DashboardProfileEditRoute: DashboardProfileEditRoute,
}

const DashboardProfileRouteWithChildren =
  DashboardProfileRoute._addFileChildren(DashboardProfileRouteChildren)

interface DashboardRouteChildren {
  DashboardApplicationsRoute: typeof DashboardApplicationsRoute
  DashboardBookmarksRoute: typeof DashboardBookmarksRoute
  DashboardCompanyRoute: typeof DashboardCompanyRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardPortfolioRoute: typeof DashboardPortfolioRoute
  DashboardProfileRoute: typeof DashboardProfileRouteWithChildren
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardJobsNewRoute: typeof DashboardJobsNewRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardJobsIdApplicationsRoute: typeof DashboardJobsIdApplicationsRoute
  DashboardJobsIdEditRoute: typeof DashboardJobsIdEditRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardApplicationsRoute: DashboardApplicationsRoute,
  DashboardBookmarksRoute: DashboardBookmarksRoute,
  DashboardCompanyRoute: DashboardCompanyRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardPortfolioRoute: DashboardPortfolioRoute,
  DashboardProfileRoute: DashboardProfileRouteWithChildren,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardJobsNewRoute: DashboardJobsNewRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardJobsIdApplicationsRoute: DashboardJobsIdApplicationsRoute,
  DashboardJobsIdEditRoute: DashboardJobsIdEditRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
